---
version: 2

jobs:
  build:
    docker:
      - image: udata/circleci:2-alpine
      - image: mongo:3.6
      - image: redis:alpine
      - image: udata/elasticsearch:2.4.5
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
          - py-cache-{{ arch }}-{{ checksum "pyproject.toml" }}
          - py-cache-{{ arch }}-{{ .Branch }}
          - py-cache-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install python dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            make deps
      - save_cache:
          key: py-cache-{{ arch }}-{{ checksum "pyproject.toml" }}
          paths:
          - venv
      - save_cache:
          key: py-cache-{{ arch }}-{{ .Branch }}
          paths:
          - venv
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            make test
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
          destination: reports
      - run:
          name: Build a distributable package
          command: |
            source venv/bin/activate
            # Build a wheel release
            make build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: udata/circleci:2-alpine
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            source venv/bin/activate
            FLIT_USERNAME=${PYPI_USERNAME} FLIT_PASSWORD=${PYPI_PASSWORD} make publish
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /[0-9]+(\.[0-9]+)+/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
